# Site settings
title: ENB
email: philippross369@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Put your notebook description here
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: thephilross
github_username:  thephilross

# disqus shortname
# disqus: ""

# Build settings
markdown: kramdown

kramdown:
  auto_ids:     true
  toc_levels:   1..3

highlighter: pygments

# show only published posts when serving remotely
unpublished: false

exclude:
    - README.md
